name: Test if buildable
on: [push, pull_request]
jobs:
  test-vars:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo SERVER
          echo ${{ vars.SERVER }}

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker-practice/actions-setup-docker@master
        timeout-minutes: 10
      - run: |
          set -x

          docker build . -t docs

          docker run --name docs -d docs

          sleep 60

          docker stop docs

  push:
    needs: [test]
    runs-on: ubuntu-latest
    if: "github.ref == 'refs/heads/main'"
    steps:
      - uses: actions/checkout@v4
      - uses: docker-practice/actions-setup-docker@master
        timeout-minutes: 10
      - run: |
          set -x

          docker build . -t docs

          docker image tag docs ${{ vars.SERVER }}/docs
          docker push ${{ vars.SERVER }}/docs
